### ISSUE TITLE
[Question]: Is there an option to disable Free move?

### ISSUE THREAD

**Issue by Lakshman1996** [hallysonh/ngx-imageviewer#74]
Hey @hallysonh the library is fantastic!.
I wanted to to know if free move can be disabled? if not is there any workaround.

**Comment by jigneshk5** [comment]
@hallysonh I have the same question

**Comment by hallysonh** [comment]
Hi guys. I haven't used this component for a long time and since then I haven't updated it anymore due to lack of time. However, I will need to use it in a new project that will start later this month. Therefore, I plan to improve and update it as much as possible. I will take this feature into account.

**Comment by hallysonh** [comment]
In short, it is not supported yet.
